config/routes.rb
Rails.application.routes.draw do
  resources :lists
  resources :builders do
    collection { post :import}
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'builders/index'

  get '/scrape', to:'lists#scrape_next_list'

root to: 'builders#index'
end

app/models/list.rb
class List < ApplicationRecord
  require 'scraped_list'
  require 'scraped_item'

  #after_create :set_builder_info
    def builder_list(start_page = 0, no_pages = 0, state = nil)
      a = ScrapedList.new.get_basic_list(:start_page => start_page, :no_pages => no_pages, :state => state)
      # binding.pry

    end


    def set_builder_info(start_page, no_pages, state = nil)
      a, b = builder_list(start_page, no_pages, state) #start_page, no_pages, url
      @fail_count = 0
      @counter = 0
      a.each do |b|
        begin
          x = ScrapedItem.new(b).create_builder
        rescue HTTParty::UnsupportedURIScheme => e
          puts " // #{e.message} ==> Failed: #{b[:company].to_s[0,15]}..."
          @fail_count += 1
        rescue => e
          puts " // #{e.message} ==> Failed: #{b[:company].to_s[0,15]}..."
          @fail_count += 1
        end
        @counter += 1
      end

      if @counter % 100 == 0
        puts @counter
      end 

      puts " "
      puts "Failed to save #{@fail_count} records"
      puts "==============================================="
      puts "Success! Builder info set for #{a.size} records"
      puts "==============================================="

      self.update_attributes(:source => b)
      self.update_attributes(:length => a.size)
      self.update_attributes(:fail_count => @fail_count)
      ::Builder.dedupe
      # self.update_attributes(:content => @list.to_s)
    end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def scrape_next_list
    @list = List.new
    @list.set_builder_info(scrape_params[:start_page], scrape_params[:no_pages])
    @list.save

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:source)
    end

    def scrape_params
      params.permit(:start_page, :no_pages, :url)
    end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%= form_with(model: list, local: true) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :source %>
    <%= form.text_field :source, id: :list_source %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lists</h1>


<table>
  <% list= @lists.first %>
    <% list.attributes.each do |attr_name, attr_value| %>
    <th> <strong><%= attr_name.titleize %></strong></th>
    <% end %>


  <% for list in @lists %>
    <tr>
      <% list.attributes.each do |attr_name, attr_value| %>
      <% if attr_value.to_f.eql?(attr_value) # trying to get differnt formats for numbers and text%>
        <td><%= number_with_delimiter(attr_value.to_f.round(2), :delimiter => ',') %></td>
      <% else %>
        <td><%= attr_value.to_s[0,40] %></td>
      <% end %>

      <% end %>

      <td><%= link_to "Show", list %></td>
      <td><%= link_to "Edit", edit_list_path(list) %></td>
      <td><%= link_to "Destroy", list, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<br>

<%= link_to 'Builders', builders_path %> |
<%= link_to 'New List', new_list_path %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Builders', builders_path %> |
<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Source:</strong>
  <%= @list.source %>
</p>


<% @list.attributes.each do |attr_name, attr_value| %>
  <% if attr_value.to_f.eql?(attr_value) # trying to get differnt formats for numbers and text%>
    <p><strong><%= attr_name.titleize %>:</strong> <%= number_with_delimiter(attr_value.to_f.round(2), :delimiter => ',') %></p>
  <% else %>
    <p><strong><%= attr_name.titleize %>:</strong> <%= attr_value %></p>
  <% end %>
<% end %>

<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Builders', builders_path %> |
<%= link_to 'Back', lists_path %>