config/routes.rb
Rails.application.routes.draw do
  resources :lists
  resources :builders do
    collection { post :import}
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'builders/index'

  get '/scrape', to:'lists#scrape_next_list'

root to: 'builders#index'
end

app/models/builder.rb
class Builder < ActiveRecord::Base

  require 'scraped_list'
  require 'scraped_item'
  require 'find_email'

  def self.dedupe
    @counter = 0
    ::Builder.all.each do |loc| #1
      ::Builder.where('url = ? AND id > ?', loc.url, loc.id).each do |comp| #2
          c1 = loc.attributes
          c2 = comp.attributes
          c1.map{ |k,v| v == nil ? c1.delete(k) : '' }
          c2.map{ |k,v| v == nil ? c2.delete(k) : '' }
          c1.merge(c2)
          loc.update(c1)
          puts "Deleted Builder ID #{comp.id}" #delete the first, assuming the later is more complete
          comp.destroy
          @counter += 1
      end #do 2
    end #do 1
    puts "============================"
    puts "Cleaned up #{@counter} duplicates"
  end

  def self.to_csv # localhost:3000/builders.csv
    attributes = %w{id contact_name company phone location site email}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |item|
        csv << attributes.map{ |attr| item.send(attr) }
      end
    end
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      r = row.encode("UTF-16be", :invalid=>:replace, :replace=>"?").encode('UTF-8')
      ::Builder.create! r.to_hash
    end
  end

  def self.split_names
    @counter = 0
    ::Builder.all.each do |loc|
      if loc.first_name.blank?
        if loc.contact_name.blank?
          next
        else
          hash = NameSplitter.new.split(loc.contact_name)
          # @name = loc.contact_name
          # parts = @name.split
          #
          # # If any part is "and", then put together the two parts around it
          # # For example, "Mr. and Mrs." or "Mickey and Minnie"
          # parts.each_with_index do |part, i|
          #   if ["and", "&"].include?(part) and i > 0
          #     p3 = parts.delete_at(i+1)
          #     p2 = parts.at(i)
          #     p1 = parts.delete_at(i-1)
          #     parts[i-1] = [p1, p2, p3].join(" ")
          #   end
          # end
          #
          # # Build a hash of the remaining parts
          # hash = {
          #   :suffix => (s = parts.pop unless parts.last !~ /(\w+\.|[IVXLM]+|[A-Z]+)$/),
          #   :last_name  => (l = parts.pop),
          #   :prefix => (p = parts.shift unless parts[0] !~ /^\w+\./),
          #   :first_name => (f = parts.shift),
          #   :middle_name => (m = parts.join(" "))
          # }
          #
          # #Reverse name if "," was used in Last, First notation.
          # if hash[:first_name] =~ /,$/
          #   hash[:first_name] = hash[:last_name]
          #   hash[:last_name] = $` # everything before the match
          # end

          hash[:first_name] ||= loc.first_name
          hash[:last_name] ||= loc.last_name

          loc.update_attributes(:first_name => hash[:first_name])
          loc.update_attributes(:last_name => hash[:last_name])
          @counter += 1
        end
      else
        next
      end
    end
    puts "============================"
    puts "Cleaned up #{@counter} names"

  end

  def self.fill_emails(limit = 50, start_index = 0)
    # do this y = FindEmail.new.get_email(Builder.first[:first_name].to_s,Builder.first[:last_name].to_s, Builder.first[:site].to_s)
    @counter = 0
    @skip_count = 0
    @email_count = 0


    ::Builder.all.drop(start_index).each do |loc|
      if loc.email.nil? || loc.email.include?("[") || loc.email.include?("60") || loc.email.blank? || loc.email.include?("null")
        if loc.first_name.blank? || loc.site.blank? || loc.site.include?("Missing") || loc.first_name.nil? || loc.site.include?("houzz")
          @skip_count += 1
        else
          @first = loc.first_name.to_s
          @last = loc.last_name.to_s
          @site = loc.site.to_s
          puts "Attempting #{@counter} out of #{limit}, #{loc.company} // #{loc.email}"
          @email = FindEmail.new.test_email_variants(@first, @last, @site)

          loc.update_attributes(:email => @email.to_s)
          @counter += 1

        end
      end

      break if @counter >= limit
    end

    puts "Updated #{@counter} emails, skipped #{@skip_count}"

    ::Builder.all.each do |loc|
      if loc.email.nil?
        next
      elsif loc.email.include?("@")
        @email_count += 1
      end
    end

    puts "In total, #{@email_count} real emails in the DB."

  end

end

app/controllers/builders_controller.rb
class BuildersController < ApplicationController
  before_action :set_builder, only: [:show, :edit, :update, :destroy]

  # GET /builders
  # GET /builders.json
  def index
    @builders = Builder.paginate(:page => params[:page], :per_page => 100) #Builder.all

    respond_to do |format|
      format.html
      format.csv { send_data @builders.to_csv, filename: "builders-#{Date.today}.csv" }
    end

  end

  # GET /builders/1
  # GET /builders/1.json
  def show
  end

  # GET /builders/new
  def new
    @builder = Builder.new
  end

  # GET /builders/1/edit
  def edit
  end

  # POST /builders
  # POST /builders.json
  def create
    @builder = Builder.new#(builder_params)

    respond_to do |format|
      if @builder.save
        format.html { redirect_to @builder, notice: 'Builder was successfully created.' }
        format.json { render :show, status: :created, location: @builder }
      else
        format.html { render :new }
        format.json { render json: @builder.errors, status: :unprocessable_entity }
      end
    end
  end

  def import
    Builder.import(params[:file])
    redirect_to root_url, notice: "Data Imported Successfully"
  end

  # PATCH/PUT /builders/1
  # PATCH/PUT /builders/1.json
  def update
    respond_to do |format|
      if @builder.update(builder_params)
        format.html { redirect_to @builder, notice: 'Builder was successfully updated.' }
        format.json { render :show, status: :ok, location: @builder }
      else
        format.html { render :edit }
        format.json { render json: @builder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /builders/1
  # DELETE /builders/1.json
  def destroy
    @builder.destroy
    respond_to do |format|
      format.html { redirect_to builders_url, notice: 'Builder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_builder
      @builder = Builder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def builder_params
      params.fetch(:builder, {})
    end
end

app/helpers/builders_helper.rb
module BuildersHelper
end

app/views/builders/_form.html.erb
<%= form_with(model: builder, local: true) do |form| %>
  <% if builder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(builder.errors.count, "error") %> prohibited this builder from being saved:</h2>

      <ul>
      <% builder.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/builders/edit.html.erb
<h1>Editing Builder</h1>

<%= render 'form', builder: @builder %>

<%= link_to 'Show', @builder %> |
<%= link_to 'Back', builders_path %>

app/views/builders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Builders</h1>

<div>
<h1> Import Data </h1>
  <%= form_tag import_builders_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Import CSV" %>
    <% end %>
</div>
<%= will_paginate @builders %>
<table>
  <% builder= @builders.first %>
    <% builder.attributes.each do |attr_name, attr_value| %>
      <% if attr_name.include?('ed_at') %>
        <% next %>
      <% else %>
      <th> <strong><%= attr_name.titleize %></strong></th>
      <% end %>
    <% end %>


  <% for builder in @builders %>
    <tr>
      <% builder.attributes.each do |attr_name, attr_value| %>
        <% if attr_name.include?('ed_at') %>
          <% next %>
        <% elsif attr_value.to_s.include?('houzz.com') %>
          <td><a href= <%= attr_value %>> <%= attr_value.to_s.gsub('https://www.houzz.com/pro','') %></a></td>
        <% else %>
          <% if attr_value.to_f.eql?(attr_value) # trying to get differnt formats for numbers and text%>
            <td><%= number_with_delimiter(attr_value.to_f.round(2), :delimiter => ',') %></td>
          <% else %>
            <td><%= attr_value.to_s[0,40] %></td>
          <% end %>
        <% end %>
      <% end %>

      <td><%= link_to "Show", builder %></td>
      <td><%= link_to "Edit", edit_builder_path(builder) %></td>
      <td><%= link_to "Destroy", builder, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>
<%= will_paginate @builders %>
<br>

<%= link_to 'New Builder', new_builder_path %>

app/views/builders/new.html.erb
<h1>New Builder</h1>

<%= render 'form', builder: @builder %>

<%= link_to 'Back', builders_path %>

app/views/builders/show.html.erb
<p id="notice"><%= notice %></p>

<% @builder.attributes.each do |attr_name, attr_value| %>
  <% if attr_value.to_f.eql?(attr_value) # trying to get differnt formats for numbers and text%>
    <p><strong><%= attr_name.titleize %>:</strong> <%= number_with_delimiter(attr_value.to_f.round(2), :delimiter => ',') %></p>
  <% else %>
    <p><strong><%= attr_name.titleize %>:</strong> <%= attr_value %></p>
  <% end %>
<% end %>

<%= link_to 'Builders', builders_path %> |

<%= link_to 'Edit', edit_builder_path(@builder) %> |
<%= link_to 'Back', builders_path %>